/**
  PARTICIONAMIENTO POR RANGO EN TABLAS
  ------------------------------------
-- ## 🧮 CLASE 166 — Creando tablas particionadas por rango

  La partición por rango divide los datos en rangos definidos por el usuario. Cada partición contiene filas cuyos valores de columna caen dentro de un rango específico.

  Sintaxis básica:
  CREATE TABLE nombre_tabla
 (
   columna1 tipo_dato,
   columna2 tipo_dato,
   ...
 )
 PARTITION BY RANGE(columna,columna1)
 (
  PARTITION P1 VALUES LESS THAN (10),
    PARTITION P2 VALUES LESS THAN (20)
  )
 */
CREATE TABLE "RANGO"
(
    CODIGO NUMBER NOT NULL,
    DATOS  VARCHAR2(100)
)
    PARTITION BY RANGE (codigo)
(
    PARTITION P1 VALUES LESS THAN (10),
    PARTITION P2 VALUES LESS THAN (20),
    PARTITION P3 VALUES LESS THAN (30),
    PARTITION P4 VALUES LESS THAN (40)
);

SELECT *
FROM RANGO;

SELECT *
FROM USER_PART_TABLES;-- VER LA TABLA PARTICIONADA

SELECT *
FROM USER_TAB_PARTITIONS
WHERE TABLE_NAME = 'RANGO';
-- VER LAS PARTICIONES DE LA TABLA


--## 🧮 CLASE 167 — Inserts y selects en tablas particionadas

INSERT INTO RANGO
VALUES (21, 'aaaa');

SELECT *
FROM RANGO;-- AQUI SE VE EL DATO INSERTADO

SELECT *
FROM RANGO PARTITION (P3);-- AQUI SE VE EL DATO INSERTADO EN LA PARTICION P3

INSERT INTO RANGO
VALUES (8, 'bbbb');

SELECT *
FROM RANGO PARTITION (P1);-- AQUI SE VE EL DATO INSERTADO EN LA PARTICION P1

SELECT *
FROM RANGO
WHERE CODIGO = 21;-- AQUI SE VE EL DATO INSERTADO

SELECT *
FROM RANGO
WHERE CODIGO > 21;
-- AQUI SE VE EL DATO INSERTADO MAYOR A 21

--## 🧮 CLASE 168 — AÑADIR PARTICIONES EN PARTICIONES POR RANGO - MAXVALUE

INSERT INTO RANGO
VALUES (40, 'KKKK');
-- ERROR PORQUE NO HAY PARTICION PARA 40

-- INSERTAMOS UNA NUEVA PARTICION
ALTER TABLE RANGO
    ADD PARTITION P5 VALUES LESS THAN (50);

-- VEMOS LAS PARTICIONES
SELECT *
FROM USER_TAB_PARTITIONS
WHERE TABLE_NAME = 'RANGO';

-- AHORA SI INSERTAMOS EL DATO
INSERT INTO RANGO
VALUES (40, 'KKKK');

SELECT *
FROM RANGO PARTITION (P5);-- AQUI SE VE EL DATO INSERTADO EN LA PARTICION P5

ALTER TABLE RANGO
    ADD PARTITION P6 VALUES LESS THAN (100);

-- PONIENDO MAXVALUE

ALTER TABLE RANGO
    ADD PARTITION P7 VALUES LESS THAN (MAXVALUE);

-- VISUALIZAR LAS PARTICIONES

SELECT *
FROM USER_TAB_PARTITIONS
WHERE TABLE_NAME = 'RANGO';

-- LUEGO DE ESTO PODRIAMOS INSERTAR CUALQUIER VALOR MAYOR A 50

--## 🧮 CLASE 169 — MODIFICAR UNA FILA EN PARTICIONES
SELECT *
FROM RANGO;

UPDATE RANGO
SET CODIGO=22
WHERE CODIGO = 21;

UPDATE RANGO
SET CODIGO=7
WHERE CODIGO = 22;
-- TE VA A DAR UN ERROR SI NO HABILITAS LA OPCION ENABLE ROW MOVEMENT

-- ENABLAMOS LA OPCION
ALTER TABLE RANGO
    ENABLE ROW MOVEMENT;

-- COMPROBAMOS QUE LA OPCION ESTA HABILITADA- NO ES REQUERIDO PERO ES BUENA PRACTICA
SELECT *
FROM RANGO PARTITION (P1);

