SELECT R.REGION_NAME
FROM REGIONS R
         LEFT JOIN COUNTRIES C ON R.REGION_ID = C.REGION_ID
         LEFT JOIN LOCATIONS L ON C.COUNTRY_ID = L.COUNTRY_ID
         LEFT JOIN DEPARTMENTS D ON L.LOCATION_ID = D.LOCATION_ID
WHERE C.COUNTRY_ID IS NULL;

-- OTRA FORMA DE HACERLO CAUSITA!!!
SELECT REGION_NAME
FROM REGIONS REGIONES
WHERE NOT EXISTS(SELECT *
                 FROM COUNTRIES
                          NATURAL JOIN LOCATIONS
                          NATURAL JOIN DEPARTMENTS
                 WHERE REGION_ID = REGIONES.REGION_ID);



